services:
  mysql8:
    container_name: movie-management
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jetbill123
      MYSQL_DATABASE: moviesdb
    volumes:
      - movies-data:/var/lib/mysql
volumes:
  movies-data: