server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  application:
    name: movie-management
  sql:
    init:
      mode: never
      data-locations: classpath:db/movies.sql, classpath:db/users.sql, classpath:/db/ratings.sql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moviesdb
    password: jetbill123
    username: root


  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
      sql:
       BasicBinder: TRACE


